# Generated by Django 5.0.6 on 2024-06-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tamanho', models.CharField(blank=True, choices=[('P', 'Pequeno'), ('G', 'Grande')], max_length=200, null=True)),
                ('valor', models.FloatField()),
                ('tipo', models.CharField(choices=[('S', 'Salgado'), ('D', 'Doce')], max_length=200)),
                ('sabor', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='donuts/')),
            ],
        ),
    ]
