# Generated by Django 5.0.6 on 2024-06-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donut',
            name='ingredientes',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
