# Generated by Django 5.0.6 on 2024-06-25 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0002_donut_ingredientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donut',
            name='tamanho',
        ),
        migrations.RemoveField(
            model_name='donut',
            name='valor',
        ),
    ]
