# Generated by Django 5.0.6 on 2024-06-25 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0003_remove_donut_tamanho_remove_donut_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donut',
            name='sabor',
        ),
    ]
