# Generated by Django 5.0.6 on 2024-06-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centos', '0002_cento_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='centos/'),
        ),
    ]
